version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  image-service:
    image: telescope_img_svc:latest
    build:
      context: ./image
      dockerfile: Dockerfile
    ports:
      - '4444'

    labels:
      - 'traefik.http.routers.image.rule=Host(`image.docker.localhost`)'
