version: '3'

services:
  # Infrastructure
  reverse-proxy:
    image: traefik:v2.4
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config/traefik.yaml:/etc/traefik/traefik.yaml"

  redis:
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis-data:/data

  # ELK Stack
  elasticsearch:
    env_file: .env
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`elastic.docker.localhost`)"
      - "traefik.http.routers.elasticsearch.middlewares=es-stripprefix"
      - "traefik.http.middlewares.es-stripprefix.stripprefix.prefixes=/es"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=${ELASTIC_PORT}"


  kibana:
    env_file: .env
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "${KIBANA_PORT}"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ELASTIC_PORT}
      - KIBANA_HOST=${KIBANA_HOST}
      - SERVER_PORT=${KIBANA_PORT}
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    labels:
      - "traefik.http.routers.kibana.rule=Host(`kibana.docker.localhost`)"
      - "traefik.backend=kibana"


  # Micro Services
  image-service:
    image: telescope_img_svc:latest
    build:
      context: ./image
      dockerfile: Dockerfile
    ports:
      - "${IMAGE_PORT}"
    labels:
      - "traefik.http.routers.image.rule=Host(`image.docker.localhost`)"


volumes:
  elasticsearch:
